components:
  cleaner:
    init_parameters:
      keep_id: false
      remove_empty_lines: true
      remove_extra_whitespaces: true
      remove_regex: null
      remove_repeated_substrings: false
      remove_substrings: null
    type: haystack.components.preprocessors.document_cleaner.DocumentCleaner
  embedder:
    init_parameters:
      batch_size: 32
      device:
        device: cpu
        type: single
      embedding_separator: '

        '
      meta_fields_to_embed:
      - title
      model: sentence-transformers/all-mpnet-base-v2
      normalize_embeddings: false
      prefix: ''
      progress_bar: true
      suffix: ''
      token:
        env_vars:
        - HF_API_TOKEN
        - HF_TOKEN
        strict: false
        type: env_var
      trust_remote_code: false
    type: haystack.components.embedders.sentence_transformers_document_embedder.SentenceTransformersDocumentEmbedder
  writer:
    init_parameters:
      document_store:
        init_parameters:
          custom_mapping: null
          embedding_similarity_function: cosine
          hosts: http://localhost:9200
          index: medium-articles
        type: haystack_integrations.document_stores.elasticsearch.document_store.ElasticsearchDocumentStore
      policy: SKIP
    type: haystack.components.writers.document_writer.DocumentWriter
connections:
- receiver: embedder.documents
  sender: cleaner.documents
- receiver: writer.documents
  sender: embedder.documents
max_loops_allowed: 100
metadata: {}
